name: chengpeng's blogs
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - run: hexo clean
      - run: hexo generate # generate static files
      - run: hexo new page tags
      - run: hexo new page categories